-- AlterTable
ALTER TABLE "LeadLyft" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3),
ALTER COLUMN "privateNote" DROP NOT NULL,
ALTER COLUMN "reason" DROP NOT NULL;
